# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e4a23c356c10452b35eeb2a06024733ab7d0315831e3bd1f942540adfeae88deab8d1a1b9ed454d43f4708c6a593eff2e170fb812e8671c15b2b722d0349ed6

test:
  secret_key_base: 8d90e53aad6954dbccb88984d79849d269253418b6757cbf469aabff91eb1f74919f927c998ad2b4f8062b34d5203d5663eabfa8e71244aa1a258b8f745ab9fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
